# Generated by Django 3.2.8 on 2021-11-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myownapp', '0002_placetwo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placetwo',
            new_name='Placeto',
        ),
    ]
